In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
df = pd.read_csv('data_set/housing_prediction.csv')

In [77]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [79]:
df['Suburb'].unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Altona Meadows', 'Ardeer', 'Attwood', 'Bayswater',
       'Bayswater North', 'Beaumaris', 'Berwick', 'Blackburn',
       'Blackburn South', 'Boronia', 'Briar Hill', 'Broadmeadows',
       'Bundoora', 'Burnside Heights', 'Burwood East', 'Cairnlea',
       'Caroline Springs', 'Cheltenham', 'Clarinda', 'Clayton',
       'Clyde North', 'Craigieburn', 'Cranbourne', 'Croydon',
       'Croydon Hills', 'Croydon North', 'Dandenong', 'Dandenong North',
       'Diamond Creek', 'Dingley Village', 'Doncaster East', 'Donvale',
       'Doreen', 'Edithvale', 'Eltham', 'Eltham North', 'Emerald',
       'Epping', 'Eumemmerring', 'Ferntree Gully', 'Forest Hill',
       'Frankston', 'Frankston North', 'Frankston South', 'Gisborne',
       'Gladstone Park', 'Glen Waverley', 'Greensborough', 'Greenvale',
       'Hallam', 'Healesville', 'Heathmont', 'Highett', 'Hillside',
       'Hoppers Crossing', 'Huntingdale', 'Keilor Downs', 'Keilor Lodge',
       'Keysborough', 'Kings Park', 'Lalor', 'Lower Plenty', 'Lynbrook',
       'MacLeod', 'Melton', 'Melton South', 'Melton West', 'Mentone',
       'Mernda', 'Mickleham', 'Mill Park', 'Mitcham', 'Montmorency',
       'Montrose', 'Mordialloc', 'Mount Waverley', 'Mulgrave',
       'Narre Warren', 'Noble Park', 'Nunawading', 'Oakleigh East',
       'Parkdale', 'Point Cook', 'Ringwood', 'Ringwood East', 'Rockbank',
       'Rowville', 'Roxburgh Park', 'Sandringham', 'Seabrook', 'Seaford',
       'Skye', 'South Morang', 'Springvale', 'Springvale South',
       'St Albans', 'St Helena', 'Sunbury', 'Sydenham', 'Tarneit',
       'Taylors Hill', 'Taylors Lakes', 'Tecoma', 'Templestowe',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Vermont South', 'Wantirna', 'Wantirna South', 'Werribee',
       'Werribee South', 'Westmeadows', 'Williams Landing', 'Wollert',
       'Wyndham Vale', 'Aspendale', 'Black Rock', 'Blackburn North',
       'Bonbeach', 'Carrum', 'Chelsea', 'Clayton South', 'Dallas',
       'Delahey', 'Doveton', 'McKinnon', 'Mooroolbark', 'Pakenham',
       'Ringwood North', 'Scoresby', 'Warrandyte', 'Watsonia North',
       'Wattle Glen', 'Wheelers Hill', 'Albanvale', 'Aspendale Gardens',
       'Belgrave', 'Carrum Downs', 'Cranbourne East', 'Cranbourne North',
       'Deer Park', 'Heatherton', 'Kilsyth', 'Langwarrin', 'Notting Hill',
       'Patterson Lakes', 'Riddells Creek', 'Beaconsfield Upper',
       'Chelsea Heights', 'Chirnside Park', 'Coolaroo', 'Darley',
       'Hampton Park', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Sandhurst', 'Silvan', 'Wallan',
       'Croydon South', 'Derrimut', 'Diggers Rest', 'Knoxfield', 'Upwey',
       'Warranwood', 'Bacchus Marsh', 'Bullengarook', 'Deepdene',
       'Hurstbridge', 'Kurunjang', 'Laverton', 'Lilydale', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Olinda', 'Waterways',
       'Beaconsfield', 'Yarra Glen', 'Brookfield', 'Lysterfield',
       'Plenty', 'Whittlesea', 'Burnside', 'New Gisborne', 'Guys Hill',
       'Plumpton', 'croydon', 'Monbulk', 'Avonsleigh', 'Wildwood',
       'Gisborne South', 'Research', 'viewbank', 'Botanic Ridge', 'Bulla',
       'Coldstream', 'Hopetoun Park', 'Cranbourne West', 'Eynesbury',
       'Fawkner Lot', 'Ferny Creek', 'Wandin North', 'Kalkallo',
       'Menzies Creek'], dtype=object)

In [80]:
categorical_columns = df.select_dtypes(include=['object']).columns

In [81]:
for feature in categorical_columns:
    print(f"Unique values in {feature}: {df[feature].unique()}")

Unique values in Suburb: ['Abbotsford' 'Airport West' 'Albert Park' 'Alphington' 'Altona'
 'Altona North' 'Armadale' 'Ascot Vale' 'Ashburton' 'Ashwood'
 'Avondale Heights' 'Balaclava' 'Balwyn' 'Balwyn North' 'Bentleigh'
 'Bentleigh East' 'Box Hill' 'Braybrook' 'Brighton' 'Brighton East'
 'Brunswick' 'Brunswick West' 'Bulleen' 'Burwood' 'Camberwell'
 'Canterbury' 'Carlton North' 'Carnegie' 'Caulfield' 'Caulfield North'
 'Caulfield South' 'Chadstone' 'Clifton Hill' 'Coburg' 'Coburg North'
 'Collingwood' 'Doncaster' 'Eaglemont' 'Elsternwick' 'Elwood' 'Essendon'
 'Essendon North' 'Fairfield' 'Fitzroy' 'Fitzroy North' 'Flemington'
 'Footscray' 'Glen Iris' 'Glenroy' 'Gowanbrae' 'Hadfield' 'Hampton'
 'Hampton East' 'Hawthorn' 'Heidelberg Heights' 'Heidelberg West'
 'Hughesdale' 'Ivanhoe' 'Kealba' 'Keilor East' 'Kensington' 'Kew'
 'Kew East' 'Kooyong' 'Maidstone' 'Malvern' 'Malvern East' 'Maribyrnong'
 'Melbourne' 'Middle Park' 'Mont Albert' 'Moonee Ponds' 'Moorabbin'
 'Newport' 'Niddrie' 'North Melbourne' 'Northcote' 'Oak Park'
 'Oakleigh South' 'Parkville' 'Pascoe Vale' 'Port Melbourne' 'Prahran'
 'Preston' 'Reservoir' 'Richmond' 'Rosanna' 'Seddon' 'South Melbourne'
 'South Yarra' 'Southbank' 'Spotswood' 'St Kilda' 'Strathmore' 'Sunshine'
 'Sunshine North' 'Sunshine West' 'Surrey Hills' 'Templestowe Lower'
 'Thornbury' 'Toorak' 'Viewbank' 'Watsonia' 'West Melbourne'
 'Williamstown' 'Williamstown North' 'Windsor' 'Yallambie' 'Yarraville'
 'Aberfeldie' 'Bellfield' 'Brunswick East' 'Burnley' 'Campbellfield'
 'Carlton' 'East Melbourne' 'Essendon West' 'Fawkner' 'Hawthorn East'
 'Heidelberg' 'Ivanhoe East' 'Jacana' 'Kingsbury' 'Kingsville'
 'Murrumbeena' 'Ormond' 'West Footscray' 'Albion' 'Brooklyn' 'Glen Huntly'
 'Oakleigh' 'Ripponlea' 'Cremorne' 'Docklands' 'South Kingsville'
 'Strathmore Heights' 'Travancore' 'Caulfield East' 'Seaholme'
 'Keilor Park' 'Gardenvale' 'Princes Hill' 'Altona Meadows' 'Ardeer'
 'Attwood' 'Bayswater' 'Bayswater North' 'Beaumaris' 'Berwick' 'Blackburn'
 'Blackburn South' 'Boronia' 'Briar Hill' 'Broadmeadows' 'Bundoora'
 'Burnside Heights' 'Burwood East' 'Cairnlea' 'Caroline Springs'
 'Cheltenham' 'Clarinda' 'Clayton' 'Clyde North' 'Craigieburn'
 'Cranbourne' 'Croydon' 'Croydon Hills' 'Croydon North' 'Dandenong'
 'Dandenong North' 'Diamond Creek' 'Dingley Village' 'Doncaster East'
 'Donvale' 'Doreen' 'Edithvale' 'Eltham' 'Eltham North' 'Emerald' 'Epping'
 'Eumemmerring' 'Ferntree Gully' 'Forest Hill' 'Frankston'
 'Frankston North' 'Frankston South' 'Gisborne' 'Gladstone Park'
 'Glen Waverley' 'Greensborough' 'Greenvale' 'Hallam' 'Healesville'
 'Heathmont' 'Highett' 'Hillside' 'Hoppers Crossing' 'Huntingdale'
 'Keilor Downs' 'Keilor Lodge' 'Keysborough' 'Kings Park' 'Lalor'
 'Lower Plenty' 'Lynbrook' 'MacLeod' 'Melton' 'Melton South' 'Melton West'
 'Mentone' 'Mernda' 'Mickleham' 'Mill Park' 'Mitcham' 'Montmorency'
 'Montrose' 'Mordialloc' 'Mount Waverley' 'Mulgrave' 'Narre Warren'
 'Noble Park' 'Nunawading' 'Oakleigh East' 'Parkdale' 'Point Cook'
 'Ringwood' 'Ringwood East' 'Rockbank' 'Rowville' 'Roxburgh Park'
 'Sandringham' 'Seabrook' 'Seaford' 'Skye' 'South Morang' 'Springvale'
 'Springvale South' 'St Albans' 'St Helena' 'Sunbury' 'Sydenham' 'Tarneit'
 'Taylors Hill' 'Taylors Lakes' 'Tecoma' 'Templestowe' 'The Basin'
 'Thomastown' 'Truganina' 'Tullamarine' 'Vermont' 'Vermont South'
 'Wantirna' 'Wantirna South' 'Werribee' 'Werribee South' 'Westmeadows'
 'Williams Landing' 'Wollert' 'Wyndham Vale' 'Aspendale' 'Black Rock'
 'Blackburn North' 'Bonbeach' 'Carrum' 'Chelsea' 'Clayton South' 'Dallas'
 'Delahey' 'Doveton' 'McKinnon' 'Mooroolbark' 'Pakenham' 'Ringwood North'
 'Scoresby' 'Warrandyte' 'Watsonia North' 'Wattle Glen' 'Wheelers Hill'
 'Albanvale' 'Aspendale Gardens' 'Belgrave' 'Carrum Downs'
 'Cranbourne East' 'Cranbourne North' 'Deer Park' 'Heatherton' 'Kilsyth'
 'Langwarrin' 'Notting Hill' 'Patterson Lakes' 'Riddells Creek'
 'Beaconsfield Upper' 'Chelsea Heights' 'Chirnside Park' 'Coolaroo'
 'Darley' 'Hampton Park' 'Keilor' 'Meadow Heights' 'Mount Evelyn'
 'North Warrandyte' 'Sandhurst' 'Silvan' 'Wallan' 'Croydon South'
 'Derrimut' 'Diggers Rest' 'Knoxfield' 'Upwey' 'Warranwood'
 'Bacchus Marsh' 'Bullengarook' 'Deepdene' 'Hurstbridge' 'Kurunjang'
 'Laverton' 'Lilydale' 'Wonga Park' 'Endeavour Hills' 'Officer' 'Olinda'
 'Waterways' 'Beaconsfield' 'Yarra Glen' 'Brookfield' 'Lysterfield'
 'Plenty' 'Whittlesea' 'Burnside' 'New Gisborne' 'Guys Hill' 'Plumpton'
 'croydon' 'Monbulk' 'Avonsleigh' 'Wildwood' 'Gisborne South' 'Research'
 'viewbank' 'Botanic Ridge' 'Bulla' 'Coldstream' 'Hopetoun Park'
 'Cranbourne West' 'Eynesbury' 'Fawkner Lot' 'Ferny Creek' 'Wandin North'
 'Kalkallo' 'Menzies Creek']
Unique values in Address: ['68 Studley St' '85 Turner St' '25 Bloomburg St' ... '147A Severn St'
 '12/37 Stephen St' '3 Tarrengower St']
Unique values in Type: ['h' 'u' 't']
Unique values in Method: ['SS' 'S' 'VB' 'SP' 'PI' 'SN' 'W' 'PN' 'SA']
Unique values in SellerG: ['Jellis' 'Biggin' 'Rounds' 'Nelson' 'Collins' 'Dingle' 'Purplebricks'
 'Greg' 'Philip' 'LITTLE' 'Kay' 'Beller' 'Marshall' 'hockingstuart' 'Brad'
 'Maddison' 'Barry' 'Airport' 'Considine' 'Rendina' 'Ray' 'Propertyau'
 'McDonald' 'Frank' 'Prof.' 'Harcourts' 'Thomson' 'Buxton' 'RT'
 "Sotheby's" 'Cayzer' 'Chisholm' 'McGrath' 'Brace' 'Miles' 'Holland'
 'Love' 'Thomas' 'Barlow' 'Sweeney' 'Village' 'Jas' 'Williams' 'Gunn&Co'
 'Burnham' 'Point' 'Compton' 'FN' 'Hunter' 'Raine&Horne' 'Noel' 'Hodges'
 'Gary' 'Fletchers' 'Woodards' 'Raine' 'Alexkarbon' 'Walshe' 'Weda'
 'Stockdale' 'Tim' 'Buxton/Marshall' 'AIME' 'Moonee' 'HAR' 'Edward' 'RW'
 'North' 'MICM' 'Ascend' 'Christopher' 'Morrison' 'Bekdon' 'Mandy' 'R&H'
 'Fletchers/One' 'Lindellas' 'Appleby' 'Assisi' 'One' 'Owen' 'Parkes'
 'C21' 'Century' "O'Brien" 'Bayside' 'Anderson' 'Paul'
 'hockingstuart/Buxton' 'Smart' 'First' 'Matthew' 'Melbourne' 'Nick'
 'Allens' 'Bells' 'Nguyen' 'Trimson' 'Douglas' 'Batty' 'GL' 'YPA'
 "Tiernan's" 'J' 'Castran' 'Branon' 'Rodney' 'Joseph' 'Harrington'
 'Galldon' 'Grantham' 'Chambers' 'Pagan' 'Peter' 'hockingstuart/Advantage'
 'Ross' 'Rayner' 'Garvey' "O'Donoghues" 'Hamilton' 'Weast' 'Kelly'
 'Property' "Private/Tiernan's" 'Australian' 'Bustin' "Abercromby's"
 'Whiting' 'iTRAK' 'Del' 'Caine' 'Nicholson' 'JMRE' 'ASL' 'Changing' 'Re'
 'RE' 'Walsh' 'Foxtons' 'Ham' 'Darren' 'Vic' 'Haughton' 'Scott' 'Pride'
 'Morleys' 'Wilson' 'Buxton/Advantage' 'Professionals' 'Joe' 'Red'
 'hockingstuart/Jellis' 'Craig' 'Naison' 'Sweeney/Advantage' 'Reach'
 'Domain' 'Eview' 'Jason' "D'Aprano" 'Charlton' 'CASTRAN' 'Wood' 'William'
 'Coventry' 'Buckingham' 'Nardella' 'Karen' 'LJ' 'Shape' 'Direct'
 'Fletchers/Fletchers' 'Besser' 'Johnston' 'Avion' 'Redina' 'Clairmont'
 'Lucas' 'Dixon' 'Xynergy' 'Elite' 'Buxton/Find' 'W.B.' 'Leased'
 'Harcourts/Barry' 'Win' 'Collings' 'New' 'Parkinson' 'Geoff'
 'hockingstuart/Barry' 'Blue' 'MSM' 'Steveway' 'hockingstuart/Village'
 'VICPROP' 'Inner' 'Meadows' 'Allan' 'S&L' 'Crane' 'Calder' 'Metro'
 'Homes' 'Zahn' 'Mason' 'Landfield' 'David' 'Luxe' 'Prowse' 'Ken'
 'Rombotis' 'iOne' 'hockingstuart/Sweeney' 'Iconek' 'Luxton' 'Hooper'
 'JRW' 'Oak' 'White' 'Jim' 'Weston' '@Realty' 'Reed' 'Oriental' 'Max'
 'Steller' 'Rosin' 'Real' 'Jeffrey' 'Hall' 'Icon' 'buyMyplace' 'WHITEFOX'
 'Christou' 'Marvelli' "Grant's" 'Hoskins' 'Gardiner' 'McLennan' 'Triwest'
 'Reliance' 'PRDNationwide' 'Only' 'Leyton' 'iSell' 'Obrien' 'Maitland'
 'Millership' 'L' 'Emerson' 'Follett' 'Ash' 'LLC' 'Ace' 'Flannagan'
 'Carter' 'WeSell' 'M.J' 'iProperty' 'Hayeswinckle' 'Schroeder' 'iHomes'
 'VICProp' 'REMAX' 'Space' 'Victory' 'Aumeca' 'Mindacom' 'Ryder'
 'Sanctuary' 'Leeburn' 'Asset' 'Westside' 'Sell' 'Mitchell' 'Darras' 'U'
 'Nicholas' 'Rexhepi' 'Keatings' 'Aquire' 'Conquest' 'Prime' 'Donovan'
 'Community' 'Free' 'Veitch' 'John' 'Peake' 'Ristic' 'JY' 'Upper' 'Daniel'
 'VicHomes' 'TRUE' 'McNaughton' 'Leading' 'Bullen' 'Better' 'Boutique'
 'Royston' 'Langwell' 'Silver' 'Wyndham' 'Kaye' 'Nicholls' 'Bowman' 'Just'
 'Home' 'Le' 'Cooper' 'Black' 'The' 'Open' 'Roger' 'McEwing' 'Sandhurst'
 'Boran' 'hockingstuart/hockingstuart' 'Area' 'MJ' 'Eric' 'SN'
 'Waterfront' 'P' 'PRD' 'Bombay' 'Quinta' 'T' 'Tanner' 'LJH' 'Munn'
 'Knight' 'Justin' 'Blackbird' 'Sweeney/Burnham' 'H' 'Alex' 'Can'
 'Pavilion' 'Benchmark' 'Gellibrand' 'hockingstuart/Harcourts' 'Charter'
 'Surreal' 'Vicprop' 'A' 'Upside' 'OBrien' 'Meallin' 'Malvern' 'Mark'
 'Bradly' 'For' 'Peninsula' 'Sutherland' 'Leaders' 'Spencer'
 'McGrath/Langwell' 'Benlor' 'Burns' 'Sterling' 'K.R.Peters'
 'Buxton/Buxton' 'CarlinSmith' 'Gold' 'Hill' 'People'
 'hockingstuart/Biggin' 'Mega' 'Skad' 'Ruralco' 'Create' 'Janice' 'R'
 'G&H' 'Commercial' 'PSP' 'hockingstuart/Cayzer' 'Unity' 'Sprint'
 'McGrath/Buxton' 'hockingstuart/Marshall' 'McGrath/First' 'voglwalpole'
 'Watermark' 'Methven']
Unique values in Date: ['3/09/2016' '3/12/2016' '4/02/2016' '4/03/2017' '4/06/2016' '6/08/2016'
 '7/05/2016' '7/11/2016' '8/10/2016' '10/12/2016' '12/11/2016'
 '13/08/2016' '14/05/2016' '15/10/2016' '16/04/2016' '16/07/2016'
 '17/09/2016' '18/03/2017' '18/06/2016' '19/11/2016' '22/05/2016'
 '22/08/2016' '23/04/2016' '24/09/2016' '25/02/2017' '26/07/2016'
 '27/11/2016' '28/05/2016' '30/07/2016' '10/09/2016' '11/02/2017'
 '27/06/2016' '28/08/2016' '12/06/2016' '11/03/2017' '28/01/2016'
 '6/05/2017' '8/04/2017' '13/05/2017' '29/04/2017' '20/05/2017'
 '22/04/2017' '1/07/2017' '3/06/2017' '17/06/2017' '24/06/2017'
 '27/05/2017' '8/07/2017' '12/08/2017' '15/07/2017' '22/07/2017'
 '29/07/2017' '3/09/2017' '9/09/2017' '16/09/2017' '19/08/2017'
 '23/09/2017' '26/08/2017' '7/10/2017' '14/10/2017' '21/10/2017'
 '28/10/2017' '30/09/2017' '4/11/2017' '11/11/2017' '18/11/2017'
 '25/11/2017' '6/01/2018' '9/12/2017' '3/02/2018' '10/02/2018'
 '20/01/2018' '27/01/2018' '3/03/2018' '10/03/2018' '17/02/2018'
 '17/03/2018' '24/02/2018']
Unique values in CouncilArea: ['Yarra City Council' 'Moonee Valley City Council'
 'Port Phillip City Council' 'Darebin City Council'
 'Hobsons Bay City Council' 'Stonnington City Council'
 'Boroondara City Council' 'Monash City Council' 'Glen Eira City Council'
 'Whitehorse City Council' 'Maribyrnong City Council'
 'Bayside City Council' 'Moreland City Council' 'Manningham City Council'
 'Melbourne City Council' 'Banyule City Council' 'Brimbank City Council'
 'Kingston City Council' 'Hume City Council' 'Knox City Council'
 'Maroondah City Council' 'Casey City Council' 'Melton City Council'
 'Greater Dandenong City Council' 'Nillumbik Shire Council'
 'Cardinia Shire Council' 'Whittlesea City Council'
 'Frankston City Council' 'Macedon Ranges Shire Council'
 'Yarra Ranges Shire Council' 'Wyndham City Council'
 'Moorabool Shire Council' 'Mitchell Shire Council' nan]
Unique values in Regionname: ['Northern Metropolitan' 'Western Metropolitan' 'Southern Metropolitan'
 'Eastern Metropolitan' 'South-Eastern Metropolitan' 'Eastern Victoria'
 'Northern Victoria' 'Western Victoria' nan]

In [82]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [83]:
columns_fill_zero = ['Bedroom2','Bathroom','Landsize','Propertycount','Distance','Postcode']

In [84]:
df[columns_fill_zero] = df[columns_fill_zero].fillna(0)

In [85]:
mean_building_area = df['BuildingArea'].mean()
df['BuildingArea'] = df['BuildingArea'].fillna(mean_building_area)

In [86]:
mean_Lattitude = df['Lattitude'].mean()
df['Lattitude'] = df['Lattitude'].fillna(mean_Lattitude)

In [87]:
mean_Longtitude = df['Longtitude'].mean()
df['Longtitude'] = df['Longtitude'].fillna(mean_Longtitude)

In [88]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             0
Postcode             0
Bedroom2             0
Bathroom             0
Car               8728
Landsize             0
BuildingArea         0
YearBuilt        19306
CouncilArea          3
Lattitude            0
Longtitude           0
Regionname           3
Propertycount        0
dtype: int64

In [89]:
mean_yr = df['YearBuilt'].mean()
df['YearBuilt'] = df['YearBuilt'].fillna(mean_yr)

In [90]:
df.dropna(inplace = True)

In [91]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Type'] = encoder.fit_transform(df['Type'])

In [92]:
df['Type']

1        0
2        0
4        0
5        0
6        0
        ..
34849    0
34852    0
34853    0
34854    1
34856    0
Name: Type, Length: 20423, dtype: int32

In [93]:
!pip install category_encoders
import category_encoders as ce

Requirement already satisfied: category_encoders in c:\users\amil\anaconda3\lib\site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (2.1.4)
Requirement already satisfied: patsy>=0.5.1 in c:\users\amil\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\amil\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\amil\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\amil\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\amil\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\amil\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\amil\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\amil\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)

In [94]:
encoder = ce.CountEncoder()

In [95]:
df['Suburb'] = encoder.fit_transform(df['Suburb'])

In [96]:
df['Suburb'].unique()

array([ 68, 102,  76,  44,  92,  78, 109, 173,  74,  65, 110,  33, 153,
       231, 205, 349,  71,  60, 243, 197, 292, 144,  95, 198,  53, 169,
        13,  40,  70,  50, 263,  89, 146, 283,  32,  55,  73, 123,  75,
       171, 250, 226,  36,  80,  45, 234, 100,  43, 129,  27, 174, 139,
         3, 116,  90, 179, 136,  47,  46,  86, 177, 101, 261,  83,  34,
       218, 180, 143, 321, 491, 312,  81, 239, 182, 147, 162, 126, 119,
        61,  42, 145,  23,  67,  30, 206,  58,  21,   9,  10,  25, 156,
       148,  35,  38,  98,  15,  22,  59,  11,  31,   8,  14,  26,  17,
        97,  16, 106, 168,  77,  19,  41,  12,  37,  93,   2,  69,  56,
         4, 127, 132,  18,  52,  29,  28, 108,  64, 121,   6,  24,  49,
        62,   5,  20,   1], dtype=int64)

In [97]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,68,85 Turner St,2,0,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,160.2564,1965.289885,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,68,25 Bloomburg St,2,0,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0000,1900.000000,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
4,68,5 Charles St,3,0,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0000,1900.000000,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
5,68,40 Federation La,3,0,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,160.2564,1965.289885,Yarra City Council,-37.79690,144.99690,Northern Metropolitan,4019.0
6,68,55a Park St,4,0,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0000,2014.000000,Yarra City Council,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,43,35 Kingscote Wy,3,0,570000.0,SP,RW,24/02/2018,25.5,3750.0,...,2.0,2.0,404.0,158.0000,2012.000000,Whittlesea City Council,-37.61031,145.03393,Northern Metropolitan,2940.0
34852,206,13 Burns St,4,0,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,160.2564,1965.289885,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,206,29A Murray St,2,0,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0000,2018.000000,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,206,147A Severn St,2,1,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0000,2000.000000,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34856,206,3 Tarrengower St,2,0,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0000,1930.000000,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [98]:
df.drop(columns = ['Address','SellerG','Date'], axis =1 , inplace = True)

In [99]:
df

,Suburb,Rooms,Type,Price,Method,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,68,2,0,1480000.0,S,2.5,3067.0,2.0,1.0,1.0,202.0,160.2564,1965.289885,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,68,2,0,1035000.0,S,2.5,3067.0,2.0,1.0,0.0,156.0,79.0000,1900.000000,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
4,68,3,0,1465000.0,SP,2.5,3067.0,3.0,2.0,0.0,134.0,150.0000,1900.000000,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
5,68,3,0,850000.0,PI,2.5,3067.0,3.0,2.0,1.0,94.0,160.2564,1965.289885,Yarra City Council,-37.79690,144.99690,Northern Metropolitan,4019.0
6,68,4,0,1600000.0,VB,2.5,3067.0,3.0,1.0,2.0,120.0,142.0000,2014.000000,Yarra City Council,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,43,3,0,570000.0,SP,25.5,3750.0,3.0,2.0,2.0,404.0,158.0000,2012.000000,Whittlesea City Council,-37.61031,145.03393,Northern Metropolitan,2940.0
34852,206,4,0,1480000.0,PI,6.3,3013.0,4.0,1.0,3.0,593.0,160.2564,1965.289885,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,206,2,0,888000.0,SP,6.3,3013.0,2.0,2.0,1.0,98.0,104.0000,2018.000000,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,206,2,1,705000.0,S,6.3,3013.0,2.0,1.0,2.0,220.0,120.0000,2000.000000,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34856,206,2,0,1020000.0,PI,6.3,3013.0,2.0,1.0,0.0,250.0,103.0000,1930.000000,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [100]:
matrix = df[['Suburb','Rooms','Type','Price','Propertycount']]
print(matrix.corr())

                 Suburb     Rooms      Type     Price  Propertycount
Suburb         1.000000 -0.117009  0.092021  0.084306       0.723570
Rooms         -0.117009  1.000000 -0.533033  0.447755      -0.060493
Type           0.092021 -0.533033  1.000000 -0.348135       0.062475
Price          0.084306  0.447755 -0.348135  1.000000      -0.050635
Propertycount  0.723570 -0.060493  0.062475 -0.050635       1.000000

In [101]:
object_cols = df.select_dtypes(include = ['object'])
dataset = pd.get_dummies(object_cols, drop_first = False)

In [102]:
dataset.isna().sum()

Method_PI                                     0
Method_S                                      0
Method_SA                                     0
Method_SP                                     0
Method_VB                                     0
CouncilArea_Banyule City Council              0
CouncilArea_Bayside City Council              0
CouncilArea_Boroondara City Council           0
CouncilArea_Brimbank City Council             0
CouncilArea_Cardinia Shire Council            0
CouncilArea_Casey City Council                0
CouncilArea_Darebin City Council              0
CouncilArea_Frankston City Council            0
CouncilArea_Glen Eira City Council            0
CouncilArea_Greater Dandenong City Council    0
CouncilArea_Hobsons Bay City Council          0
CouncilArea_Hume City Council                 0
CouncilArea_Kingston City Council             0
CouncilArea_Knox City Council                 0
CouncilArea_Macedon Ranges Shire Council      0
CouncilArea_Manningham City Council           0
CouncilArea_Maribyrnong City Council          0
CouncilArea_Maroondah City Council            0
CouncilArea_Melbourne City Council            0
CouncilArea_Melton City Council               0
CouncilArea_Mitchell Shire Council            0
CouncilArea_Monash City Council               0
CouncilArea_Moonee Valley City Council        0
CouncilArea_Moorabool Shire Council           0
CouncilArea_Moreland City Council             0
CouncilArea_Nillumbik Shire Council           0
CouncilArea_Port Phillip City Council         0
CouncilArea_Stonnington City Council          0
CouncilArea_Whitehorse City Council           0
CouncilArea_Whittlesea City Council           0
CouncilArea_Wyndham City Council              0
CouncilArea_Yarra City Council                0
CouncilArea_Yarra Ranges Shire Council        0
Regionname_Eastern Metropolitan               0
Regionname_Eastern Victoria                   0
Regionname_Northern Metropolitan              0
Regionname_Northern Victoria                  0
Regionname_South-Eastern Metropolitan         0
Regionname_Southern Metropolitan              0
Regionname_Western Metropolitan               0
Regionname_Western Victoria                   0
dtype: int64

In [103]:
dataset.isna().sum()

Method_PI                                     0
Method_S                                      0
Method_SA                                     0
Method_SP                                     0
Method_VB                                     0
CouncilArea_Banyule City Council              0
CouncilArea_Bayside City Council              0
CouncilArea_Boroondara City Council           0
CouncilArea_Brimbank City Council             0
CouncilArea_Cardinia Shire Council            0
CouncilArea_Casey City Council                0
CouncilArea_Darebin City Council              0
CouncilArea_Frankston City Council            0
CouncilArea_Glen Eira City Council            0
CouncilArea_Greater Dandenong City Council    0
CouncilArea_Hobsons Bay City Council          0
CouncilArea_Hume City Council                 0
CouncilArea_Kingston City Council             0
CouncilArea_Knox City Council                 0
CouncilArea_Macedon Ranges Shire Council      0
CouncilArea_Manningham City Council           0
CouncilArea_Maribyrnong City Council          0
CouncilArea_Maroondah City Council            0
CouncilArea_Melbourne City Council            0
CouncilArea_Melton City Council               0
CouncilArea_Mitchell Shire Council            0
CouncilArea_Monash City Council               0
CouncilArea_Moonee Valley City Council        0
CouncilArea_Moorabool Shire Council           0
CouncilArea_Moreland City Council             0
CouncilArea_Nillumbik Shire Council           0
CouncilArea_Port Phillip City Council         0
CouncilArea_Stonnington City Council          0
CouncilArea_Whitehorse City Council           0
CouncilArea_Whittlesea City Council           0
CouncilArea_Wyndham City Council              0
CouncilArea_Yarra City Council                0
CouncilArea_Yarra Ranges Shire Council        0
Regionname_Eastern Metropolitan               0
Regionname_Eastern Victoria                   0
Regionname_Northern Metropolitan              0
Regionname_Northern Victoria                  0
Regionname_South-Eastern Metropolitan         0
Regionname_Southern Metropolitan              0
Regionname_Western Metropolitan               0
Regionname_Western Victoria                   0
dtype: int64

In [104]:
# Identify boolean columns
bool_cols = dataset.select_dtypes(include=['bool']).columns
print("Boolean Columns:")
print(bool_cols)

Boolean Columns:
Index(['Method_PI', 'Method_S', 'Method_SA', 'Method_SP', 'Method_VB',
       'CouncilArea_Banyule City Council', 'CouncilArea_Bayside City Council',
       'CouncilArea_Boroondara City Council',
       'CouncilArea_Brimbank City Council',
       'CouncilArea_Cardinia Shire Council', 'CouncilArea_Casey City Council',
       'CouncilArea_Darebin City Council',
       'CouncilArea_Frankston City Council',
       'CouncilArea_Glen Eira City Council',
       'CouncilArea_Greater Dandenong City Council',
       'CouncilArea_Hobsons Bay City Council', 'CouncilArea_Hume City Council',
       'CouncilArea_Kingston City Council', 'CouncilArea_Knox City Council',
       'CouncilArea_Macedon Ranges Shire Council',
       'CouncilArea_Manningham City Council',
       'CouncilArea_Maribyrnong City Council',
       'CouncilArea_Maroondah City Council',
       'CouncilArea_Melbourne City Council', 'CouncilArea_Melton City Council',
       'CouncilArea_Mitchell Shire Council', 'CouncilArea_Monash City Council',
       'CouncilArea_Moonee Valley City Council',
       'CouncilArea_Moorabool Shire Council',
       'CouncilArea_Moreland City Council',
       'CouncilArea_Nillumbik Shire Council',
       'CouncilArea_Port Phillip City Council',
       'CouncilArea_Stonnington City Council',
       'CouncilArea_Whitehorse City Council',
       'CouncilArea_Whittlesea City Council',
       'CouncilArea_Wyndham City Council', 'CouncilArea_Yarra City Council',
       'CouncilArea_Yarra Ranges Shire Council',
       'Regionname_Eastern Metropolitan', 'Regionname_Eastern Victoria',
       'Regionname_Northern Metropolitan', 'Regionname_Northern Victoria',
       'Regionname_South-Eastern Metropolitan',
       'Regionname_Southern Metropolitan', 'Regionname_Western Metropolitan',
       'Regionname_Western Victoria'],
      dtype='object')

In [105]:
dataset[bool_cols] = dataset[bool_cols].astype(int)

In [106]:
dataset[bool_cols] = dataset[bool_cols].astype(int)
dataset

,Method_PI,Method_S,Method_SA,Method_SP,Method_VB,CouncilArea_Banyule City Council,CouncilArea_Bayside City Council,CouncilArea_Boroondara City Council,CouncilArea_Brimbank City Council,CouncilArea_Cardinia Shire Council,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
34852,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34853,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34854,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34856,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [107]:
dataset

,Method_PI,Method_S,Method_SA,Method_SP,Method_VB,CouncilArea_Banyule City Council,CouncilArea_Bayside City Council,CouncilArea_Boroondara City Council,CouncilArea_Brimbank City Council,CouncilArea_Cardinia Shire Council,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
34852,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34853,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34854,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34856,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [108]:
df_combined = pd.concat([df, dataset], axis=1)
df_combined

,Suburb,Rooms,Type,Price,Method,Distance,Postcode,Bedroom2,Bathroom,Car,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,68,2,0,1480000.0,S,2.5,3067.0,2.0,1.0,1.0,...,1,0,0,0,1,0,0,0,0,0
2,68,2,0,1035000.0,S,2.5,3067.0,2.0,1.0,0.0,...,1,0,0,0,1,0,0,0,0,0
4,68,3,0,1465000.0,SP,2.5,3067.0,3.0,2.0,0.0,...,1,0,0,0,1,0,0,0,0,0
5,68,3,0,850000.0,PI,2.5,3067.0,3.0,2.0,1.0,...,1,0,0,0,1,0,0,0,0,0
6,68,4,0,1600000.0,VB,2.5,3067.0,3.0,1.0,2.0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,43,3,0,570000.0,SP,25.5,3750.0,3.0,2.0,2.0,...,0,0,0,0,1,0,0,0,0,0
34852,206,4,0,1480000.0,PI,6.3,3013.0,4.0,1.0,3.0,...,0,0,0,0,0,0,0,0,1,0
34853,206,2,0,888000.0,SP,6.3,3013.0,2.0,2.0,1.0,...,0,0,0,0,0,0,0,0,1,0
34854,206,2,1,705000.0,S,6.3,3013.0,2.0,1.0,2.0,...,0,0,0,0,0,0,0,0,1,0
34856,206,2,0,1020000.0,PI,6.3,3013.0,2.0,1.0,0.0,...,0,0,0,0,0,0,0,0,1,0

In [109]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20423 entries, 1 to 34856
Data columns (total 64 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Suburb                                      20423 non-null  int64
 1   Rooms                                       20423 non-null  int64
 2   Type                                        20423 non-null  int32
 3   Price                                       20423 non-null  float64
 4   Method                                      20423 non-null  object
 5   Distance                                    20423 non-null  float64
 6   Postcode                                    20423 non-null  float64
 7   Bedroom2                                    20423 non-null  float64
 8   Bathroom                                    20423 non-null  float64
 9   Car                                         20423 non-null  float64
 10  Landsize                                    20423 non-null  float64
 11  BuildingArea                                20423 non-null  float64
 12  YearBuilt                                   20423 non-null  float64
 13  CouncilArea                                 20423 non-null  object
 14  Lattitude                                   20423 non-null  float64
 15  Longtitude                                  20423 non-null  float64
 16  Regionname                                  20423 non-null  object
 17  Propertycount                               20423 non-null  float64
 18  Method_PI                                   20423 non-null  int32
 19  Method_S                                    20423 non-null  int32
 20  Method_SA                                   20423 non-null  int32
 21  Method_SP                                   20423 non-null  int32
 22  Method_VB                                   20423 non-null  int32
 23  CouncilArea_Banyule City Council            20423 non-null  int32
 24  CouncilArea_Bayside City Council            20423 non-null  int32
 25  CouncilArea_Boroondara City Council         20423 non-null  int32
 26  CouncilArea_Brimbank City Council           20423 non-null  int32
 27  CouncilArea_Cardinia Shire Council          20423 non-null  int32
 28  CouncilArea_Casey City Council              20423 non-null  int32
 29  CouncilArea_Darebin City Council            20423 non-null  int32
 30  CouncilArea_Frankston City Council          20423 non-null  int32
 31  CouncilArea_Glen Eira City Council          20423 non-null  int32
 32  CouncilArea_Greater Dandenong City Council  20423 non-null  int32
 33  CouncilArea_Hobsons Bay City Council        20423 non-null  int32
 34  CouncilArea_Hume City Council               20423 non-null  int32
 35  CouncilArea_Kingston City Council           20423 non-null  int32
 36  CouncilArea_Knox City Council               20423 non-null  int32
 37  CouncilArea_Macedon Ranges Shire Council    20423 non-null  int32
 38  CouncilArea_Manningham City Council         20423 non-null  int32
 39  CouncilArea_Maribyrnong City Council        20423 non-null  int32
 40  CouncilArea_Maroondah City Council          20423 non-null  int32
 41  CouncilArea_Melbourne City Council          20423 non-null  int32
 42  CouncilArea_Melton City Council             20423 non-null  int32
 43  CouncilArea_Mitchell Shire Council          20423 non-null  int32
 44  CouncilArea_Monash City Council             20423 non-null  int32
 45  CouncilArea_Moonee Valley City Council      20423 non-null  int32
 46  CouncilArea_Moorabool Shire Council         20423 non-null  int32
 47  CouncilArea_Moreland City Council           20423 non-null  int32
 48  CouncilArea_Nillumbik Shire Council         20423 non-null  int32
 49  CouncilArea_Port Phillip City Council       20423 non-null  int32
 50  CouncilArea_Stonnington City Council        20423 non-null  int32
 51  CouncilArea_Whitehorse City Council         20423 non-null  int32
 52  CouncilArea_Whittlesea City Council         20423 non-null  int32
 53  CouncilArea_Wyndham City Council            20423 non-null  int32
 54  CouncilArea_Yarra City Council              20423 non-null  int32
 55  CouncilArea_Yarra Ranges Shire Council      20423 non-null  int32
 56  Regionname_Eastern Metropolitan             20423 non-null  int32
 57  Regionname_Eastern Victoria                 20423 non-null  int32
 58  Regionname_Northern Metropolitan            20423 non-null  int32
 59  Regionname_Northern Victoria                20423 non-null  int32
 60  Regionname_South-Eastern Metropolitan       20423 non-null  int32
 61  Regionname_Southern Metropolitan            20423 non-null  int32
 62  Regionname_Western Metropolitan             20423 non-null  int32
 63  Regionname_Western Victoria                 20423 non-null  int32
dtypes: float64(12), int32(47), int64(2), object(3)
memory usage: 6.5+ MB

In [110]:
obj_cols = df_combined.select_dtypes(include=['object']).columns

# Step 2: Drop object-type columns from the DataFrame
df_combined.drop(columns=obj_cols, inplace=True)

In [111]:
df_combined

,Suburb,Rooms,Type,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,68,2,0,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,...,1,0,0,0,1,0,0,0,0,0
2,68,2,0,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,...,1,0,0,0,1,0,0,0,0,0
4,68,3,0,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,...,1,0,0,0,1,0,0,0,0,0
5,68,3,0,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,...,1,0,0,0,1,0,0,0,0,0
6,68,4,0,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,43,3,0,570000.0,25.5,3750.0,3.0,2.0,2.0,404.0,...,0,0,0,0,1,0,0,0,0,0
34852,206,4,0,1480000.0,6.3,3013.0,4.0,1.0,3.0,593.0,...,0,0,0,0,0,0,0,0,1,0
34853,206,2,0,888000.0,6.3,3013.0,2.0,2.0,1.0,98.0,...,0,0,0,0,0,0,0,0,1,0
34854,206,2,1,705000.0,6.3,3013.0,2.0,1.0,2.0,220.0,...,0,0,0,0,0,0,0,0,1,0
34856,206,2,0,1020000.0,6.3,3013.0,2.0,1.0,0.0,250.0,...,0,0,0,0,0,0,0,0,1,0

In [112]:
x = df_combined.drop('Price', axis = 1)
y = df_combined['Price']
x

,Suburb,Rooms,Type,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,68,2,0,2.5,3067.0,2.0,1.0,1.0,202.0,160.2564,...,1,0,0,0,1,0,0,0,0,0
2,68,2,0,2.5,3067.0,2.0,1.0,0.0,156.0,79.0000,...,1,0,0,0,1,0,0,0,0,0
4,68,3,0,2.5,3067.0,3.0,2.0,0.0,134.0,150.0000,...,1,0,0,0,1,0,0,0,0,0
5,68,3,0,2.5,3067.0,3.0,2.0,1.0,94.0,160.2564,...,1,0,0,0,1,0,0,0,0,0
6,68,4,0,2.5,3067.0,3.0,1.0,2.0,120.0,142.0000,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34849,43,3,0,25.5,3750.0,3.0,2.0,2.0,404.0,158.0000,...,0,0,0,0,1,0,0,0,0,0
34852,206,4,0,6.3,3013.0,4.0,1.0,3.0,593.0,160.2564,...,0,0,0,0,0,0,0,0,1,0
34853,206,2,0,6.3,3013.0,2.0,2.0,1.0,98.0,104.0000,...,0,0,0,0,0,0,0,0,1,0
34854,206,2,1,6.3,3013.0,2.0,1.0,2.0,220.0,120.0000,...,0,0,0,0,0,0,0,0,1,0
34856,206,2,0,6.3,3013.0,2.0,1.0,0.0,250.0,103.0000,...,0,0,0,0,0,0,0,0,1,0

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [114]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30)

In [115]:
print(x.shape)  # (num_samples, num_features)
print(y.shape)  # (num_samples,)

(20423, 60)
(20423,)

In [116]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [117]:
score = reg.score(x_test,y_test)
print(score)

0.4282414507698119

In [118]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

In [119]:
estimator = Lasso()
params = {'alpha': [1e-15,1e-10,1e-8,1e-2,1,45,50,55,60,64,70,75,100]}
lasso_reg = GridSearchCV(estimator, params,cv = 4)

In [120]:
lasso_reg.fit(x_train,y_train)

C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.757e+14, tolerance: 4.419e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.051e+14, tolerance: 4.503e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.150e+14, tolerance: 4.523e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.331e+14, tolerance: 4.548e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.687e+14, tolerance: 4.419e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.959e+14, tolerance: 4.503e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.073e+14, tolerance: 4.523e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.276e+14, tolerance: 4.548e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.057e+14, tolerance: 4.419e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.197e+14, tolerance: 4.503e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.520e+14, tolerance: 4.523e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.341e+14, tolerance: 4.548e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.058e+14, tolerance: 4.419e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.734e+14, tolerance: 4.503e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.227e+14, tolerance: 4.523e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.342e+14, tolerance: 4.548e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.682e+14, tolerance: 4.419e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.734e+14, tolerance: 4.503e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.777e+14, tolerance: 4.523e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.790e+14, tolerance: 4.548e+11
  model = cd_fast.enet_coordinate_descent(
C:\Users\amil\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.332e+14, tolerance: 5.998e+11
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=4, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 45, 50, 55, 60,
                                   64, 70, 75, 100]})

In [121]:
print(lasso_reg.best_params_)
print(lasso_reg.best_score_)

{'alpha': 1}
0.6347981563616281